### ISSUE TITLE
classesDir property

### ISSUE THREAD

**Issue by kwinata** [bmuschko/gradle-in-action-source#11]
https://github.com/bmuschko/gradle-in-action-source/blob/4b65643fd2f3dd0fe4c145fec1f9d1ea8182f319/chapter03/todo-app-external-dependency/build.gradle#L22

classesDir should be classesDirs (https://discuss.gradle.org/t/could-not-get-unknown-property-classesdir-for-main-classes-of-type-org-gradle-api-internal-tasks-defaultsourcesetoutput/30570)

**Comment by bmuschko** [comment]
The `classesDir` property is only available in newer versions of Gradle. I believe this was added in Gradle 5.x. This project is still [based on Gradle 1.7](https://github.com/bmuschko/gradle-in-action-source/blob/master/gradle/wrapper/gradle-wrapper.properties) and therefore cannot be upgraded to the new version as that's the code referenced in the book.
