### ISSUE TITLE
Would the book content still be useful for nowadays' software development?

### ISSUE THREAD

**Issue by AndyLau223** [bmuschko/gradle-in-action-source#14]
Dear author, hope you are doing well.

I'm a beginner of gradle, I'd know more about Gradle to automate my software packaging and deployment. I'm just wondering that is the book still can apply to today's software development? thanks!

**Comment by bmuschko** [comment]
General concepts still apply and you would still be able to learn from the book. The Gradle API and some of the plugins have changed quite a bit and therefore you should read up on the Gradle documentation in parallel.

**Comment by AndyLau223** [comment]
Thank you for the information. It's very useful especially for a beginner.
