### ISSUE TITLE
Why you use com.yuege.gia.todo.*？

### ISSUE THREAD

**Issue by ge1mina023** [bmuschko/gradle-in-action-source#8]

**Comment by bmuschko** [comment]
Can you explain what you are referring to or point me to the file that uses this import or package name? The default package for all example code in this repository should be `com.manning.gia`.

**Comment by ge1mina023** [comment]
Thank you. I just have a question, What is the meaning of manning.gia?

**Comment by bmuschko** [comment]
`com.manning` == [Manning Publications](https://manning.com/), the original publisher of the book
`gia` == short for "Gradle in Action"

**Comment by ge1mina023** [comment]
Thanks！
